substitutions:
  device_name: esp-rolety-ogrod-zimowy
  friendly_name: Rolety Ogrod Zimowy

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "ESPSomfy-RTS — pre-built firmware, not compiled via esphome"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
