substitutions:
  device_name: monitor-zbiornika
  friendly_name: Monitor zbiornika

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    advanced:
      sram1_as_iram: true

logger:
  level: INFO

api:
  encryption:
    key: !secret monitor_zbiornika_api_key

ota:
  - platform: esphome
    password: !secret monitor_zbiornika_ota_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

web_server:
  port: 80

uart:
  id: tank_uart
  rx_pin: GPIO5
  tx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 1

one_wire:
  - platform: gpio
    id: ds18b20_bus
    pin:
      number: GPIO33
      mode:
        input: true
        pullup: true

sensor:
  - platform: a02yyuw
    uart_id: tank_uart
    name: "Odleglosc w zbiorniku"
    id: odleglosc_w_zbiorniku
    unit_of_measurement: "m"
    accuracy_decimals: 2
    device_class: distance
    state_class: measurement
    filters:
      - lambda: return x / 1000.0;
      - throttle: 1s

  - platform: pulse_meter
    id: przeplyw_wody
    name: "Przeplyw wody"
    pin:
      number: GPIO32
      mode:
        input: true
        pullup: true
    internal_filter: 100us
    timeout: 10s
    unit_of_measurement: "L/min"
    accuracy_decimals: 2
    device_class: volume_flow_rate
    state_class: measurement
    filters:
      - multiply: 0.0034722222
      - throttle_average: 5s
    total:
      name: "Przeplyw wody suma"
      id: przeplyw_wody_suma
      unit_of_measurement: "L"
      accuracy_decimals: 2
      device_class: volume
      state_class: total_increasing
      filters:
        - multiply: 0.0034722222

  - platform: dallas_temp
    one_wire_id: ds18b20_bus
    name: "Temperatura zbiornika 1"
    id: temperatura_zbiornika_1
    resolution: 12
    update_interval: 30s
