substitutions:
  device_name: monitor-zbiornika
  friendly_name: Monitor zbiornika

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    advanced:
      sram1_as_iram: true

logger:
  level: INFO

api:
  encryption:
    key: !secret monitor_zbiornika_api_key

ota:
  - platform: esphome
    password: !secret monitor_zbiornika_ota_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

web_server:
  port: 80

uart:
  id: tank_uart
  rx_pin: GPIO5
  tx_pin: GPIO17
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: a02yyuw
    uart_id: tank_uart
    name: "Odleglosc w zbiorniku"
    id: odleglosc_w_zbiorniku
    unit_of_measurement: "m"
    accuracy_decimals: 2
    device_class: distance
    state_class: measurement
    filters:
      - lambda: return x / 1000.0;
      - throttle: 1s
